### ISSUE TITLE
How to use in template?

### ISSUE THREAD

**Issue by kodeine** [rajan-g/angular2-letter-avatar#2]
hello,
is there a way to use it in template without writing code in component? like i include the directive and in template i do like, `[avatardata]=name`?

Thanks

**Comment by rajan-g** [comment]
yes, you can hard code your json object

**Comment by kodeine** [comment]
@rajan-g can you give me an example how to use this in a template only?
something like this maybe `<img [data]='first name' />`?

**Comment by Muthu2020** [comment]
You can use like this 

> `<avatar  [avatardata]="avatarDataSquare"></avatar>`

You have to provide options inside of avatarDataSquare object.
The object look like this: {
               size: 100,
               background: '#F39C12', // by default it will produce dynamic colors
                fontColor: '#FFFFFF',
                border: "2px solid #d3d3d3",
                isSquare: true,
                text: "Rajan Gunasekaran"
}
